#############################################################################
# Makefile for building: ICP
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  ICP/ICP.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile ICP/ICP.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -IICP -I. -IICP -IICP -IICP/ClassDiagram -IICP/SequenceDiagram -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ICP1.0.0
DISTDIR = /homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/.tmp/ICP1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ICP/ClassDiagram/aggregation.cpp \
		ICP/ClassDiagram/classdiagram.cpp \
		ICP/ClassDiagram/composition.cpp \
		ICP/ClassDiagram/association.cpp \
		ICP/ClassDiagram/generalization.cpp \
		ICP/ClassDiagram/metaclass.cpp \
		ICP/ClassDiagram/metaclassattribute.cpp \
		ICP/ClassDiagram/metaclassmethod.cpp \
		ICP/ClassDiagram/metaclassobject.cpp \
		ICP/ClassDiagram/relation.cpp \
		ICP/SequenceDiagram/sequenceactivation.cpp \
		ICP/SequenceDiagram/sequencedeactivation.cpp \
		ICP/SequenceDiagram/sequencediagram.cpp \
		ICP/SequenceDiagram/sequenceevent.cpp \
		ICP/SequenceDiagram/sequencelifeline.cpp \
		ICP/SequenceDiagram/sequencemessage.cpp \
		ICP/SequenceDiagram/sequencereturn.cpp \
		ICP/SequenceDiagram/sequencespacer.cpp \
		ICP/classdiagramscene.cpp \
		ICP/classgraphicsobject.cpp \
		ICP/environment.cpp \
		ICP/eventdialog.cpp \
		ICP/lifelinedialog.cpp \
		ICP/lifelinegraphicsobject.cpp \
		ICP/main.cpp \
		ICP/mainwindow.cpp \
		ICP/newclassform.cpp \
		ICP/relationgraphicsobject.cpp \
		ICP/sequencediagramscene.cpp qrc_icons.cpp \
		moc_classdiagramscene.cpp \
		moc_classgraphicsobject.cpp \
		moc_eventdialog.cpp \
		moc_lifelinedialog.cpp \
		moc_lifelinegraphicsobject.cpp \
		moc_mainwindow.cpp \
		moc_newclassform.cpp \
		moc_relationgraphicsobject.cpp \
		moc_sequencediagramscene.cpp
OBJECTS       = aggregation.o \
		classdiagram.o \
		composition.o \
		association.o \
		generalization.o \
		metaclass.o \
		metaclassattribute.o \
		metaclassmethod.o \
		metaclassobject.o \
		relation.o \
		sequenceactivation.o \
		sequencedeactivation.o \
		sequencediagram.o \
		sequenceevent.o \
		sequencelifeline.o \
		sequencemessage.o \
		sequencereturn.o \
		sequencespacer.o \
		classdiagramscene.o \
		classgraphicsobject.o \
		environment.o \
		eventdialog.o \
		lifelinedialog.o \
		lifelinegraphicsobject.o \
		main.o \
		mainwindow.o \
		newclassform.o \
		relationgraphicsobject.o \
		sequencediagramscene.o \
		qrc_icons.o \
		moc_classdiagramscene.o \
		moc_classgraphicsobject.o \
		moc_eventdialog.o \
		moc_lifelinedialog.o \
		moc_lifelinegraphicsobject.o \
		moc_mainwindow.o \
		moc_newclassform.o \
		moc_relationgraphicsobject.o \
		moc_sequencediagramscene.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		ICP/ICP/ClassDiagram/classdiagram.pri \
		ICP/ICP/SequenceDiagram/sequencediagram.pri \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		ICP/ICP/ICP.pro ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/composition.h \
		ICP/ClassDiagram/aggregation.h \
		ICP/ClassDiagram/association.h \
		ICP/ClassDiagram/generalization.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ICP/classdiagramscene.h \
		ICP/classgraphicsobject.h \
		ICP/environment.h \
		ICP/eventdialog.h \
		ICP/graphicsenum.h \
		ICP/lifelinedialog.h \
		ICP/lifelinegraphicsobject.h \
		ICP/mainwindow.h \
		ICP/newclassform.h \
		ICP/relationgraphicsobject.h \
		ICP/sequencediagramscene.h ICP/ClassDiagram/aggregation.cpp \
		ICP/ClassDiagram/classdiagram.cpp \
		ICP/ClassDiagram/composition.cpp \
		ICP/ClassDiagram/association.cpp \
		ICP/ClassDiagram/generalization.cpp \
		ICP/ClassDiagram/metaclass.cpp \
		ICP/ClassDiagram/metaclassattribute.cpp \
		ICP/ClassDiagram/metaclassmethod.cpp \
		ICP/ClassDiagram/metaclassobject.cpp \
		ICP/ClassDiagram/relation.cpp \
		ICP/SequenceDiagram/sequenceactivation.cpp \
		ICP/SequenceDiagram/sequencedeactivation.cpp \
		ICP/SequenceDiagram/sequencediagram.cpp \
		ICP/SequenceDiagram/sequenceevent.cpp \
		ICP/SequenceDiagram/sequencelifeline.cpp \
		ICP/SequenceDiagram/sequencemessage.cpp \
		ICP/SequenceDiagram/sequencereturn.cpp \
		ICP/SequenceDiagram/sequencespacer.cpp \
		ICP/classdiagramscene.cpp \
		ICP/classgraphicsobject.cpp \
		ICP/environment.cpp \
		ICP/eventdialog.cpp \
		ICP/lifelinedialog.cpp \
		ICP/lifelinegraphicsobject.cpp \
		ICP/main.cpp \
		ICP/mainwindow.cpp \
		ICP/newclassform.cpp \
		ICP/relationgraphicsobject.cpp \
		ICP/sequencediagramscene.cpp
QMAKE_TARGET  = ICP
DESTDIR       = 
TARGET        = ICP


first: all
####### Build rules

$(TARGET): ui_event_activation.h ui_event_deactivation.h ui_event_message.h ui_event_return.h ui_event_spacer.h ui_eventdialog.h ui_lifelinedialog.h ui_mainwindow.h ui_newclassform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ICP/ICP.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		ICP/ClassDiagram/classdiagram.pri \
		ICP/SequenceDiagram/sequencediagram.pri \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		ICP/ICP.pro \
		ICP/icons.qrc \
		/lib64/libQt5Widgets.prl \
		/lib64/libQt5Gui.prl \
		/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile ICP/ICP.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
ICP/ClassDiagram/classdiagram.pri:
ICP/SequenceDiagram/sequencediagram.pri:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
ICP/ICP.pro:
ICP/icons.qrc:
/lib64/libQt5Widgets.prl:
/lib64/libQt5Gui.prl:
/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ICP/ICP.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ICP/icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ICP/ClassDiagram/classdiagram.h ICP/ClassDiagram/composition.h ICP/ClassDiagram/aggregation.h ICP/ClassDiagram/association.h ICP/ClassDiagram/generalization.h ICP/ClassDiagram/metaclass.h ICP/ClassDiagram/metaclassattribute.h ICP/ClassDiagram/metaclassmethod.h ICP/ClassDiagram/metaclassobject.h ICP/ClassDiagram/relation.h ICP/SequenceDiagram/sequenceactivation.h ICP/SequenceDiagram/sequencedeactivation.h ICP/SequenceDiagram/sequencediagram.h ICP/SequenceDiagram/sequenceevent.h ICP/SequenceDiagram/sequencelifeline.h ICP/SequenceDiagram/sequencemessage.h ICP/SequenceDiagram/sequencereturn.h ICP/SequenceDiagram/sequencespacer.h ICP/classdiagramscene.h ICP/classgraphicsobject.h ICP/environment.h ICP/eventdialog.h ICP/graphicsenum.h ICP/lifelinedialog.h ICP/lifelinegraphicsobject.h ICP/mainwindow.h ICP/newclassform.h ICP/relationgraphicsobject.h ICP/sequencediagramscene.h $(DISTDIR)/
	$(COPY_FILE) --parents ICP/ClassDiagram/aggregation.cpp ICP/ClassDiagram/classdiagram.cpp ICP/ClassDiagram/composition.cpp ICP/ClassDiagram/association.cpp ICP/ClassDiagram/generalization.cpp ICP/ClassDiagram/metaclass.cpp ICP/ClassDiagram/metaclassattribute.cpp ICP/ClassDiagram/metaclassmethod.cpp ICP/ClassDiagram/metaclassobject.cpp ICP/ClassDiagram/relation.cpp ICP/SequenceDiagram/sequenceactivation.cpp ICP/SequenceDiagram/sequencedeactivation.cpp ICP/SequenceDiagram/sequencediagram.cpp ICP/SequenceDiagram/sequenceevent.cpp ICP/SequenceDiagram/sequencelifeline.cpp ICP/SequenceDiagram/sequencemessage.cpp ICP/SequenceDiagram/sequencereturn.cpp ICP/SequenceDiagram/sequencespacer.cpp ICP/classdiagramscene.cpp ICP/classgraphicsobject.cpp ICP/environment.cpp ICP/eventdialog.cpp ICP/lifelinedialog.cpp ICP/lifelinegraphicsobject.cpp ICP/main.cpp ICP/mainwindow.cpp ICP/newclassform.cpp ICP/relationgraphicsobject.cpp ICP/sequencediagramscene.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ICP/event_activation.ui ICP/event_deactivation.ui ICP/event_message.ui ICP/event_return.ui ICP/event_spacer.ui ICP/eventdialog.ui ICP/lifelinedialog.ui ICP/mainwindow.ui ICP/newclassform.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: ICP/icons.qrc \
		/usr/lib64/qt5/bin/rcc \
		ICP/arrowdown.png \
		ICP/icon.png \
		ICP/close.png \
		ICP/arrowup.png \
		ICP/plus.png
	/usr/lib64/qt5/bin/rcc -name icons ICP/icons.qrc -o qrc_icons.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_classdiagramscene.cpp moc_classgraphicsobject.cpp moc_eventdialog.cpp moc_lifelinedialog.cpp moc_lifelinegraphicsobject.cpp moc_mainwindow.cpp moc_newclassform.cpp moc_relationgraphicsobject.cpp moc_sequencediagramscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_classdiagramscene.cpp moc_classgraphicsobject.cpp moc_eventdialog.cpp moc_lifelinedialog.cpp moc_lifelinegraphicsobject.cpp moc_mainwindow.cpp moc_newclassform.cpp moc_relationgraphicsobject.cpp moc_sequencediagramscene.cpp
moc_classdiagramscene.cpp: ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/newclassform.h \
		ICP/classgraphicsobject.h \
		ICP/relationgraphicsobject.h \
		ICP/graphicsenum.h \
		ICP/classdiagramscene.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/classdiagramscene.h -o moc_classdiagramscene.cpp

moc_classgraphicsobject.cpp: ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/newclassform.h \
		ICP/classgraphicsobject.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/classgraphicsobject.h -o moc_classgraphicsobject.cpp

moc_eventdialog.cpp: ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ICP/eventdialog.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/eventdialog.h -o moc_eventdialog.cpp

moc_lifelinedialog.cpp: ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/lifelinedialog.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/lifelinedialog.h -o moc_lifelinedialog.cpp

moc_lifelinegraphicsobject.cpp: ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/lifelinegraphicsobject.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/lifelinegraphicsobject.h -o moc_lifelinegraphicsobject.cpp

moc_mainwindow.cpp: ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/classdiagramscene.h \
		ICP/newclassform.h \
		ICP/classgraphicsobject.h \
		ICP/relationgraphicsobject.h \
		ICP/graphicsenum.h \
		ICP/sequencediagramscene.h \
		ICP/lifelinedialog.h \
		ICP/lifelinegraphicsobject.h \
		ICP/eventdialog.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ICP/mainwindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/mainwindow.h -o moc_mainwindow.cpp

moc_newclassform.cpp: ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/newclassform.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/newclassform.h -o moc_newclassform.cpp

moc_relationgraphicsobject.cpp: ICP/classgraphicsobject.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/newclassform.h \
		ICP/ClassDiagram/relation.h \
		ICP/relationgraphicsobject.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/relationgraphicsobject.h -o moc_relationgraphicsobject.cpp

moc_sequencediagramscene.cpp: ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/lifelinedialog.h \
		ICP/lifelinegraphicsobject.h \
		ICP/eventdialog.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ICP/graphicsenum.h \
		ICP/sequencediagramscene.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/ClassDiagram -I/homes/eva/xh/xhorac19/Dokumenty/ICP/proj2022/ICP2/ICP/SequenceDiagram -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include ICP/sequencediagramscene.h -o moc_sequencediagramscene.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_event_activation.h ui_event_deactivation.h ui_event_message.h ui_event_return.h ui_event_spacer.h ui_eventdialog.h ui_lifelinedialog.h ui_mainwindow.h ui_newclassform.h
compiler_uic_clean:
	-$(DEL_FILE) ui_event_activation.h ui_event_deactivation.h ui_event_message.h ui_event_return.h ui_event_spacer.h ui_eventdialog.h ui_lifelinedialog.h ui_mainwindow.h ui_newclassform.h
ui_event_activation.h: ICP/event_activation.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/event_activation.ui -o ui_event_activation.h

ui_event_deactivation.h: ICP/event_deactivation.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/event_deactivation.ui -o ui_event_deactivation.h

ui_event_message.h: ICP/event_message.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/event_message.ui -o ui_event_message.h

ui_event_return.h: ICP/event_return.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/event_return.ui -o ui_event_return.h

ui_event_spacer.h: ICP/event_spacer.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/event_spacer.ui -o ui_event_spacer.h

ui_eventdialog.h: ICP/eventdialog.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/eventdialog.ui -o ui_eventdialog.h

ui_lifelinedialog.h: ICP/lifelinedialog.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/lifelinedialog.ui -o ui_lifelinedialog.h

ui_mainwindow.h: ICP/mainwindow.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/mainwindow.ui -o ui_mainwindow.h

ui_newclassform.h: ICP/newclassform.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ICP/newclassform.ui -o ui_newclassform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

aggregation.o: ICP/ClassDiagram/aggregation.cpp ICP/ClassDiagram/aggregation.h \
		ICP/ClassDiagram/relation.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aggregation.o ICP/ClassDiagram/aggregation.cpp

classdiagram.o: ICP/ClassDiagram/classdiagram.cpp ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classdiagram.o ICP/ClassDiagram/classdiagram.cpp

composition.o: ICP/ClassDiagram/composition.cpp ICP/ClassDiagram/composition.h \
		ICP/ClassDiagram/relation.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o composition.o ICP/ClassDiagram/composition.cpp

association.o: ICP/ClassDiagram/association.cpp ICP/ClassDiagram/association.h \
		ICP/ClassDiagram/relation.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o association.o ICP/ClassDiagram/association.cpp

generalization.o: ICP/ClassDiagram/generalization.cpp ICP/ClassDiagram/generalization.h \
		ICP/ClassDiagram/relation.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generalization.o ICP/ClassDiagram/generalization.cpp

metaclass.o: ICP/ClassDiagram/metaclass.cpp ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaclass.o ICP/ClassDiagram/metaclass.cpp

metaclassattribute.o: ICP/ClassDiagram/metaclassattribute.cpp ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/metaclassobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaclassattribute.o ICP/ClassDiagram/metaclassattribute.cpp

metaclassmethod.o: ICP/ClassDiagram/metaclassmethod.cpp ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaclassmethod.o ICP/ClassDiagram/metaclassmethod.cpp

metaclassobject.o: ICP/ClassDiagram/metaclassobject.cpp ICP/ClassDiagram/metaclassobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaclassobject.o ICP/ClassDiagram/metaclassobject.cpp

relation.o: ICP/ClassDiagram/relation.cpp ICP/ClassDiagram/relation.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relation.o ICP/ClassDiagram/relation.cpp

sequenceactivation.o: ICP/SequenceDiagram/sequenceactivation.cpp ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequenceactivation.o ICP/SequenceDiagram/sequenceactivation.cpp

sequencedeactivation.o: ICP/SequenceDiagram/sequencedeactivation.cpp ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencedeactivation.o ICP/SequenceDiagram/sequencedeactivation.cpp

sequencediagram.o: ICP/SequenceDiagram/sequencediagram.cpp ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencediagram.o ICP/SequenceDiagram/sequencediagram.cpp

sequenceevent.o: ICP/SequenceDiagram/sequenceevent.cpp ICP/SequenceDiagram/sequenceevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequenceevent.o ICP/SequenceDiagram/sequenceevent.cpp

sequencelifeline.o: ICP/SequenceDiagram/sequencelifeline.cpp ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencelifeline.o ICP/SequenceDiagram/sequencelifeline.cpp

sequencemessage.o: ICP/SequenceDiagram/sequencemessage.cpp ICP/SequenceDiagram/sequencemessage.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencemessage.o ICP/SequenceDiagram/sequencemessage.cpp

sequencereturn.o: ICP/SequenceDiagram/sequencereturn.cpp ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencereturn.o ICP/SequenceDiagram/sequencereturn.cpp

sequencespacer.o: ICP/SequenceDiagram/sequencespacer.cpp ICP/SequenceDiagram/sequencespacer.h \
		ICP/SequenceDiagram/sequenceevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencespacer.o ICP/SequenceDiagram/sequencespacer.cpp

classdiagramscene.o: ICP/classdiagramscene.cpp ICP/classdiagramscene.h \
		ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/newclassform.h \
		ICP/classgraphicsobject.h \
		ICP/relationgraphicsobject.h \
		ICP/graphicsenum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classdiagramscene.o ICP/classdiagramscene.cpp

classgraphicsobject.o: ICP/classgraphicsobject.cpp ICP/classgraphicsobject.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/newclassform.h \
		ICP/ClassDiagram/relation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classgraphicsobject.o ICP/classgraphicsobject.cpp

environment.o: ICP/environment.cpp ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/SequenceDiagram/sequencereturn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o environment.o ICP/environment.cpp

eventdialog.o: ICP/eventdialog.cpp ICP/eventdialog.h \
		ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ui_eventdialog.h \
		ui_event_activation.h \
		ui_event_deactivation.h \
		ui_event_message.h \
		ui_event_return.h \
		ui_event_spacer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventdialog.o ICP/eventdialog.cpp

lifelinedialog.o: ICP/lifelinedialog.cpp ICP/lifelinedialog.h \
		ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ui_lifelinedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lifelinedialog.o ICP/lifelinedialog.cpp

lifelinegraphicsobject.o: ICP/lifelinegraphicsobject.cpp ICP/lifelinegraphicsobject.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lifelinegraphicsobject.o ICP/lifelinegraphicsobject.cpp

main.o: ICP/main.cpp ICP/mainwindow.h \
		ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/classdiagramscene.h \
		ICP/newclassform.h \
		ICP/classgraphicsobject.h \
		ICP/relationgraphicsobject.h \
		ICP/graphicsenum.h \
		ICP/sequencediagramscene.h \
		ICP/lifelinedialog.h \
		ICP/lifelinegraphicsobject.h \
		ICP/eventdialog.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ICP/main.cpp

mainwindow.o: ICP/mainwindow.cpp ICP/mainwindow.h \
		ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/classdiagramscene.h \
		ICP/newclassform.h \
		ICP/classgraphicsobject.h \
		ICP/relationgraphicsobject.h \
		ICP/graphicsenum.h \
		ICP/sequencediagramscene.h \
		ICP/lifelinedialog.h \
		ICP/lifelinegraphicsobject.h \
		ICP/eventdialog.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ICP/mainwindow.cpp

newclassform.o: ICP/newclassform.cpp ICP/newclassform.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ui_newclassform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newclassform.o ICP/newclassform.cpp

relationgraphicsobject.o: ICP/relationgraphicsobject.cpp ICP/relationgraphicsobject.h \
		ICP/classgraphicsobject.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/newclassform.h \
		ICP/ClassDiagram/relation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relationgraphicsobject.o ICP/relationgraphicsobject.cpp

sequencediagramscene.o: ICP/sequencediagramscene.cpp ICP/sequencediagramscene.h \
		ICP/environment.h \
		ICP/ClassDiagram/classdiagram.h \
		ICP/ClassDiagram/metaclass.h \
		ICP/ClassDiagram/metaclassmethod.h \
		ICP/ClassDiagram/metaclassobject.h \
		ICP/ClassDiagram/metaclassattribute.h \
		ICP/ClassDiagram/relation.h \
		ICP/SequenceDiagram/sequencediagram.h \
		ICP/SequenceDiagram/sequencelifeline.h \
		ICP/SequenceDiagram/sequenceevent.h \
		ICP/SequenceDiagram/sequenceactivation.h \
		ICP/SequenceDiagram/sequencedeactivation.h \
		ICP/SequenceDiagram/sequencemessage.h \
		ICP/lifelinedialog.h \
		ICP/lifelinegraphicsobject.h \
		ICP/eventdialog.h \
		ICP/SequenceDiagram/sequencereturn.h \
		ICP/SequenceDiagram/sequencespacer.h \
		ICP/graphicsenum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencediagramscene.o ICP/sequencediagramscene.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_classdiagramscene.o: moc_classdiagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_classdiagramscene.o moc_classdiagramscene.cpp

moc_classgraphicsobject.o: moc_classgraphicsobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_classgraphicsobject.o moc_classgraphicsobject.cpp

moc_eventdialog.o: moc_eventdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventdialog.o moc_eventdialog.cpp

moc_lifelinedialog.o: moc_lifelinedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lifelinedialog.o moc_lifelinedialog.cpp

moc_lifelinegraphicsobject.o: moc_lifelinegraphicsobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lifelinegraphicsobject.o moc_lifelinegraphicsobject.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_newclassform.o: moc_newclassform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newclassform.o moc_newclassform.cpp

moc_relationgraphicsobject.o: moc_relationgraphicsobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_relationgraphicsobject.o moc_relationgraphicsobject.cpp

moc_sequencediagramscene.o: moc_sequencediagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sequencediagramscene.o moc_sequencediagramscene.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ICP/bin || mkdir -p $(INSTALL_ROOT)/opt/ICP/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ICP/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ICP/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ICP/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

